var data2020 =
  {
    year:2020,
    data:[
      {
        month:2,
        data:[
          {
            name:"ふじわら",
            spike:{
              total:10,
              point:5,
              miss:2
            },
            serve:{
              total:10,
              point:5,
              miss:4
            },
            receive:{
              total:10,
              a:2,
              b:4,
              miss:1
            },
            block:{
              total:10,
              point:5,
              miss:4
            },
          },
          {
            name:"いけだ",
            spike:{
              total:5,
              point:2,
              miss:2
            },
            serve:{
              total:10,
              point:5,
              miss:4
            },
            receive:{
              total:10,
              a:2,
              b:4,
              miss:1
            },
            block:{
              total:10,
              point:5,
              miss:4
            },
          },
        ]
      }
    ]
  };
