var data = [
  {
    year:2019,
    month:1,
    data:[
      {
        name:"しんや",
        spike:{
          total:10,
          point:5,
          miss:3
        },
        serve:{
          total:10,
          point:5,
          miss:4
        },
        receive:{
          total:10,
          a:2,
          b:4,
          miss:1
        },
        block:{
          total:10,
          point:5,
          miss:4
        },
        set:[
          {
            spike:{
              total:10,
              point:5,
              miss:3
            },
            serve:{
              total:10,
              point:5,
              miss:4
            },
            receive:{
              total:10,
              point:5,
              miss:4
            },
            block:{
              total:10,
              point:5,
              miss:4
            }
          },
          {
            spike:{
              total:10,
              point:5,
              miss:3
            },
            serve:{
              total:10,
              point:5,
              miss:4
            },
            receive:{
              total:10,
              point:5,
              miss:4
            },
            block:{
              total:10,
              point:5,
              miss:4
            }
          }
        ]
      },
    ]
  },
  {
    year:2019,
    month:2,
    data:[
      {
        name:"しんや",
        spike:{
          total:10,
          point:5,
          miss:4
        },
        serve:{
          total:10,
          point:5,
          miss:4
        },
        receive:{
          total:10,
          point:5,
          miss:4
        },
        block:{
          total:10,
          point:5,
          miss:4
        }
      },
    ]
  },  
  {
    year:2020,
    month:1,
    data:[
      {
        name:"しんや",
        spike:{
          total:10,
          point:5,
          miss:4
        },
        serve:{
          total:10,
          point:5,
          miss:4
        },
        receive:{
          total:10,
          point:5,
          miss:4
        },
        block:{
          total:10,
          point:5,
          miss:4
        }
      },
    ]
  },
];
