var data2019 = 
  {
    year:2019,
    data:[
      {
        month:1,
        data:[
          {
            name:"しんや",
            spike:{
              total:10,
              point:5,
              miss:2
            },
            serve:{
              total:10,
              point:5,
              miss:4
            },
            receive:{
              total:10,
              a:2,
              b:4,
              miss:1
            },
            block:{
              total:10,
              point:5,
              miss:4
            },
          },
          {
            name:"ひーちゃん",
            spike:{
              total:5,
              point:2,
              miss:2
            },
            serve:{
              total:10,
              point:5,
              miss:4
            },
            receive:{
              total:10,
              a:2,
              b:4,
              miss:1
            },
            block:{
              total:10,
              point:5,
              miss:4
            },
          },
        ]
      }
    ]
  };
